import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Poppins } from "next/font/google";
import Providers from "@/components/providers";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    display: "swap",
    variable: "--font-poppins",
    adjustFontFallback: false,
});

export const metadata: Metadata = {
    title: "Snippy",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${poppins.variable} overflow-x-hidden antialiased`}>
                <Providers>
                    <main>{children}</main>
                    <Toaster position="top-right" />
                </Providers>
            </body>
        </html>
    );
}
